package model.items;
import java.util.*;

/**
 * Generic representation of the 'Item' entity. Items can take on many forms.
 * They have a name, cost and an effect range (min-max). This effect is just an
 * integer, and it's usage is context dependent. It could be damage, or healing, 
 * or defence -- depends on the child.
 */
public abstract class Item
{
    public static final String SPACING = "     ";

    private int cost;
    protected String name;
    protected int minEffect;
    protected int maxEffect;

    /**
     * Constructor.
     * @param inName The item's name
     * @param inCost The item's cost
     * @param inMinEff Minimum effect
     * @param inMinEff Maximum effect
     */
    public Item(String inName, int inCost, int inMinEff, int inMaxEff)
    {
        if (inName.isEmpty())
        {
            throw new IllegalArgumentException(
                "Item must have a name"
            );
        }
        
        if (inCost <= 0)
        {
            throw new IllegalArgumentException(
                "Item must be worth at least 1 G"
            );
        }

        if (inMaxEff < inMinEff)
        {
            throw new IllegalArgumentException(
                "Max effect should be >= Min effect"
            );
        }

        if (inMaxEff < 0 || inMinEff < 0)
        {
            throw new IllegalArgumentException(
                "Min and Max Effects should be positive integers"
            );
        }

        name = inName;
        cost = inCost;
        minEffect = inMinEff;
        maxEffect = inMaxEff;
    }

    /**
     * Use the item.
     * @return The effect generated by the item between min-max
     */
    public int getEffect(Random randGenerator)
    {
        int eff = randGenerator.nextInt(maxEffect + 1 - minEffect) + minEffect;
        return eff;
    }

    public String getEffectRange()
    {
        return minEffect + " - " + maxEffect;
    }

    /**
     * Cost accessor.
     * @return The item's cost
     */
    public int getCost()
    {
        return cost;
    } 

    protected int getMin()
    {
        return minEffect;
    }

    protected int getMax()
    {
        return maxEffect;
    }
    
    abstract public String toString();
}