package model.items;
import java.util.*;

/**
 * Generic representation of the 'Item' entity. Items can take on many forms.
 * They have a name, cost and an effect range (min-max). This effect is just an
 * integer, and it's usage is context dependent. It could be damage, or healing, 
 * or defence -- depends on the child.
 */
public abstract class Item
{
    private String name;
    private int cost;
    protected int minEffect;
    protected int maxEffect;

    /**
     * Constructor.
     * @param inName The item's name
     * @param inCost The item's cost
     * @param inMinEff Minimum effect
     * @param inMinEff Maximum effect
     */
    public Item(String inName, int inCost, int inMinEff, int inMaxEff)
    {
        if (inName.isEmpty())
        {
            throw new IllegalArgumentException(
                "Item must have a name"
            );
        }
        
        if (inCost <= 0)
        {
            throw new IllegalArgumentException(
                "Item must be worth at least 1 G"
            );
        }

        if (inMaxEff < inMinEff)
        {
            throw new IllegalArgumentException(
                "Max effect should be >= Min effect"
            );
        }

        name = inName;
        cost = inCost;
        minEffect = inMinEff;
        maxEffect = inMaxEff;
    }

    /**
     * Use the item.
     * @return The effect generated by the item between min-max
     */
    public int getEffect(Random randGenerator)
    {
        int eff = randGenerator.nextInt(maxEffect + 1 - minEffect) + minEffect;
        return eff;
    }

    /**
     * Name accessor.
     * @return The item's name
     */
    public String getName()
    {
        return name;
    }

    /**
     * Cost accessor.
     * @return The item's cost
     */
    public int getCost()
    {
        return cost;
    } 

    /**
     * Range accessor
     * @return The item's effect range
     */
    public String getEffectRange()
    {
        return minEffect + " - " + maxEffect;
    } 

    /**
     * A simple string representation of the item
     * @return A String containing the attributes
     */
    public String toString()
    {
        return name;
    }
}