package model.items;
import model.characters.GameCharacter;

/**
 * Generic representation of the 'Item' entity. Items can take on many forms.
 * They have a name, cost and an effect range (min-max).
 * Because there are a number of ways a character can interact with an item,
 * based on the type of item in question, an abstarct method "interactWith()" 
 * must be implemented for each Subclass.
 */
public abstract class Item
{
    private int cost;
    protected String name;
    protected int minEffect;
    protected int maxEffect;

    /**
     * Constructor.
     * @param inName The item's name
     * @param inCost The item's cost
     * @param inMinEff Minimum effect
     * @param inMinEff Maximum effect
     */
    public Item(String inName, int inCost, int inMinEff, int inMaxEff)
    {
        // Validate imports
        if (inName.isEmpty())
        {
            throw new IllegalArgumentException(
                "Item must have a name"
            );
        }
        else if (inCost <= 0)
        {
            throw new IllegalArgumentException(
                "Item must be worth at least 1 G"
            );
        }
        else if (inMaxEff < 0 || inMinEff < 0)
        {
            throw new IllegalArgumentException(
                "Min and Max Effects should be positive integers"
            );
        }
        else if (inMaxEff < inMinEff)
        {
            throw new IllegalArgumentException(
                "Max effect should be >= Min effect"
            );
        }

        // Set everything
        name = inName;
        cost = inCost;
        minEffect = inMinEff;
        maxEffect = inMaxEff;
    }

    /**
     * Use the item.
     * @return The effect generated by the item between min-max
     */
    public int getEffect(Dice dice)
    {
        int eff = dice.roll(minEffect, maxEffect);
        return eff;
    }

    public int getCost()
    {
        return cost;
    } 

    public String getEffectRange()
    {
        return minEffect + " - " + maxEffect;
    }

    public int getMin()
    {
        return minEffect;
    }

    public int getMax()
    {
        return maxEffect;
    }
    
    public String toString()
    {
        return name;
    }

    abstract public int interactWith(GameCharacter character) throws ItemInteractionException;
}